name: first
on: push
jobs:
  job1:
    needs: job2
    name: first_job
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v3
      - name: step2
        run: "env | sort"
      - run: 'date' 
  job2:
    name: second_job
    runs-on: windows-latest
    steps:
      - name: step1
        uses: actions/checkout@v3
      - name: step2
        run: "dir Env: | sort-object"
      - run: get-date