name: secrets

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo secret
      run: echo ${{ secrets.FIRST_SECRET }} > ./test.txt &&  cat ./test.txt
    - name: ls  secretv2
      run: ls -als 
    - name: echo secretv2
      run: cat ./test.txt
    - name: Upload artifact for linux
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test
        path: ./test.txt
      
